/*DROP DATABASE IF EXISTS u698943981_nbook;*/
CREATE DATABASE IF NOT EXISTS u698943981_nbook;

USE u698943981_nbook;
DROP TABLE IF EXISTS POSTS;
CREATE TABLE POSTS(
	id INT(10) unsigned NOT NULL AUTO_INCREMENT,
	title TEXT COLLATE latin1_spanish_ci NULL,
	text TEXT COLLATE latin1_spanish_ci NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci 
AUTO_INCREMENT=1;